server:
  port: 80
#eureka 配置
eureka:
  client:
    register-with-eureka: false #是否向注册中心注册自己
    service-url:
      #单机：defaulZone :http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群：
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/