server:
  port: 8002
#mybatis配置  配置mapper对应位置
mybatis:
  type-aliases-package: com.springcloud.pojo;
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#spring配置
spring:
  application:
    name: springclou-provider-dept    #服务名一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#Eureka配置
eureka:
  client:
    service-url: #监控页面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-Procider-dept8002

info:
  app:name: MHj-springclou
  company.name: blog.MHjStudy.com